apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: botb-db
  name: botb-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: botb-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: botb-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: botb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13
          name: botb-db
          ports:
            - containerPort: 5423
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
            - mountPath: /docker-entrypoint-initdb.d/init_db.sql
              name: botb-db-cm1
              subPath: init_db.sql
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - configMap:
            items:
              - key: init_db.sql
                path: init_db.sql
            name: botb-db-cm1
          name: botb-db-cm1
