apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: botb-frontend
  name: botb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: botb-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: botb-frontend
    spec:
      containers:
        - env:
            - name: BACKEND_URL
              value: http://botb-backend:8080
          image: botb-frontend
          name: botb-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
