services:
  botb-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: botb-frontend
    environment:
      - BACKEND_URL=http://botb-backend:8080
    ports:
      - "40080:3000"
    depends_on:
      - botb-backend
      - botb-db

  botb-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: botb-backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=botb
    depends_on:
      - botb-db

  botb-db:
    image: postgres:13
    container_name: botb-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: botb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_data:
